name: Check validation scripts

on: [push]

jobs:
  test_validation_scripts:
    name: Test that the validation scripts work as expected
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - run: pip3 install -r .github/scripts/python/requirements.txt

      - run: python3 .github/scripts/python/test_unpack_entities.py

      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'

      - run: cd go/genesis-tools && go test -v ./...
